// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"
#include "Vtop.h"
#include "Vtop___024root.h"
#include "Vtop_weft_axi_pkg.h"

// FUNCTIONS
Vtop__Syms::~Vtop__Syms()
{

    // Tear down scope hierarchy
    __Vhier.remove(0, &__Vscope_weft_axi_mux_flat);
    __Vhier.remove(0, &__Vscope_weft_axi_pkg);
    __Vhier.remove(&__Vscope_weft_axi_mux_flat, &__Vscope_weft_axi_mux_flat__i_mux);
    __Vhier.remove(&__Vscope_weft_axi_mux_flat__i_mux, &__Vscope_weft_axi_mux_flat__i_mux__i_ar_arb);
    __Vhier.remove(&__Vscope_weft_axi_mux_flat__i_mux, &__Vscope_weft_axi_mux_flat__i_mux__i_aw_arb);
    __Vhier.remove(&__Vscope_weft_axi_mux_flat__i_mux, &__Vscope_weft_axi_mux_flat__i_mux__i_wfifo);
    __Vhier.remove(&__Vscope_weft_axi_mux_flat__i_mux, &__Vscope_weft_axi_mux_flat__i_mux__unnamedblk1);
    __Vhier.remove(&__Vscope_weft_axi_mux_flat__i_mux, &__Vscope_weft_axi_mux_flat__i_mux__unnamedblk2);
    __Vhier.remove(&__Vscope_weft_axi_mux_flat__i_mux__i_ar_arb, &__Vscope_weft_axi_mux_flat__i_mux__i_ar_arb__g_rr);
    __Vhier.remove(&__Vscope_weft_axi_mux_flat__i_mux__i_ar_arb__g_rr, &__Vscope_weft_axi_mux_flat__i_mux__i_ar_arb__g_rr__unnamedblk1);
    __Vhier.remove(&__Vscope_weft_axi_mux_flat__i_mux__i_aw_arb, &__Vscope_weft_axi_mux_flat__i_mux__i_aw_arb__g_rr);
    __Vhier.remove(&__Vscope_weft_axi_mux_flat__i_mux__i_aw_arb__g_rr, &__Vscope_weft_axi_mux_flat__i_mux__i_aw_arb__g_rr__unnamedblk1);

}

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup module instances
    , TOP{this, namep}
    , TOP__weft_axi_pkg{this, Verilated::catName(namep, "weft_axi_pkg")}
{
        // Check resources
        Verilated::stackCheck(31);
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    TOP.__PVT__weft_axi_pkg = &TOP__weft_axi_pkg;
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    TOP__weft_axi_pkg.__Vconfigure(true);
    // Setup scopes
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_weft_axi_mux_flat.configure(this, name(), "weft_axi_mux_flat", "weft_axi_mux_flat", "weft_axi_mux_flat", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_weft_axi_mux_flat__i_mux.configure(this, name(), "weft_axi_mux_flat.i_mux", "i_mux", "weft_axi_mux", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_weft_axi_mux_flat__i_mux__i_ar_arb.configure(this, name(), "weft_axi_mux_flat.i_mux.i_ar_arb", "i_ar_arb", "weft_rr_arbiter", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_weft_axi_mux_flat__i_mux__i_ar_arb__g_rr.configure(this, name(), "weft_axi_mux_flat.i_mux.i_ar_arb.g_rr", "g_rr", "<null>", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_weft_axi_mux_flat__i_mux__i_ar_arb__g_rr__unnamedblk1.configure(this, name(), "weft_axi_mux_flat.i_mux.i_ar_arb.g_rr.unnamedblk1", "unnamedblk1", "<null>", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_weft_axi_mux_flat__i_mux__i_aw_arb.configure(this, name(), "weft_axi_mux_flat.i_mux.i_aw_arb", "i_aw_arb", "weft_rr_arbiter", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_weft_axi_mux_flat__i_mux__i_aw_arb__g_rr.configure(this, name(), "weft_axi_mux_flat.i_mux.i_aw_arb.g_rr", "g_rr", "<null>", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_weft_axi_mux_flat__i_mux__i_aw_arb__g_rr__unnamedblk1.configure(this, name(), "weft_axi_mux_flat.i_mux.i_aw_arb.g_rr.unnamedblk1", "unnamedblk1", "<null>", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_weft_axi_mux_flat__i_mux__i_wfifo.configure(this, name(), "weft_axi_mux_flat.i_mux.i_wfifo", "i_wfifo", "weft_sync_fifo", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_weft_axi_mux_flat__i_mux__unnamedblk1.configure(this, name(), "weft_axi_mux_flat.i_mux.unnamedblk1", "unnamedblk1", "<null>", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_weft_axi_mux_flat__i_mux__unnamedblk2.configure(this, name(), "weft_axi_mux_flat.i_mux.unnamedblk2", "unnamedblk2", "<null>", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_weft_axi_pkg.configure(this, name(), "weft_axi_pkg", "weft_axi_pkg", "weft_axi_pkg", -9, VerilatedScope::SCOPE_PACKAGE);

    // Set up scope hierarchy
    __Vhier.add(0, &__Vscope_weft_axi_mux_flat);
    __Vhier.add(0, &__Vscope_weft_axi_pkg);
    __Vhier.add(&__Vscope_weft_axi_mux_flat, &__Vscope_weft_axi_mux_flat__i_mux);
    __Vhier.add(&__Vscope_weft_axi_mux_flat__i_mux, &__Vscope_weft_axi_mux_flat__i_mux__i_ar_arb);
    __Vhier.add(&__Vscope_weft_axi_mux_flat__i_mux, &__Vscope_weft_axi_mux_flat__i_mux__i_aw_arb);
    __Vhier.add(&__Vscope_weft_axi_mux_flat__i_mux, &__Vscope_weft_axi_mux_flat__i_mux__i_wfifo);
    __Vhier.add(&__Vscope_weft_axi_mux_flat__i_mux, &__Vscope_weft_axi_mux_flat__i_mux__unnamedblk1);
    __Vhier.add(&__Vscope_weft_axi_mux_flat__i_mux, &__Vscope_weft_axi_mux_flat__i_mux__unnamedblk2);
    __Vhier.add(&__Vscope_weft_axi_mux_flat__i_mux__i_ar_arb, &__Vscope_weft_axi_mux_flat__i_mux__i_ar_arb__g_rr);
    __Vhier.add(&__Vscope_weft_axi_mux_flat__i_mux__i_ar_arb__g_rr, &__Vscope_weft_axi_mux_flat__i_mux__i_ar_arb__g_rr__unnamedblk1);
    __Vhier.add(&__Vscope_weft_axi_mux_flat__i_mux__i_aw_arb, &__Vscope_weft_axi_mux_flat__i_mux__i_aw_arb__g_rr);
    __Vhier.add(&__Vscope_weft_axi_mux_flat__i_mux__i_aw_arb__g_rr, &__Vscope_weft_axi_mux_flat__i_mux__i_aw_arb__g_rr__unnamedblk1);

    // Setup export functions
    for (int __Vfinal = 0; __Vfinal < 2; ++__Vfinal) {
        __Vscope_TOP.varInsert(__Vfinal,"clk_i", &(TOP.clk_i), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_araddr", &(TOP.m_axi_araddr), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_arburst", &(TOP.m_axi_arburst), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_arcache", &(TOP.m_axi_arcache), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_arid", &(TOP.m_axi_arid), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_arlen", &(TOP.m_axi_arlen), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_arlock", &(TOP.m_axi_arlock), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_arprot", &(TOP.m_axi_arprot), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_arready", &(TOP.m_axi_arready), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_arsize", &(TOP.m_axi_arsize), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_arvalid", &(TOP.m_axi_arvalid), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_awaddr", &(TOP.m_axi_awaddr), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_awburst", &(TOP.m_axi_awburst), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_awcache", &(TOP.m_axi_awcache), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_awid", &(TOP.m_axi_awid), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_awlen", &(TOP.m_axi_awlen), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_awlock", &(TOP.m_axi_awlock), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_awprot", &(TOP.m_axi_awprot), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_awready", &(TOP.m_axi_awready), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_awsize", &(TOP.m_axi_awsize), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_awvalid", &(TOP.m_axi_awvalid), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_bid", &(TOP.m_axi_bid), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_bready", &(TOP.m_axi_bready), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_bresp", &(TOP.m_axi_bresp), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_bvalid", &(TOP.m_axi_bvalid), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_rdata", &(TOP.m_axi_rdata), false, VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_rid", &(TOP.m_axi_rid), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_rlast", &(TOP.m_axi_rlast), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_rready", &(TOP.m_axi_rready), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_rresp", &(TOP.m_axi_rresp), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_rvalid", &(TOP.m_axi_rvalid), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_wdata", &(TOP.m_axi_wdata), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_wlast", &(TOP.m_axi_wlast), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_wready", &(TOP.m_axi_wready), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_wstrb", &(TOP.m_axi_wstrb), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"m_axi_wvalid", &(TOP.m_axi_wvalid), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"rst_ni", &(TOP.rst_ni), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_araddr", &(TOP.s0_axi_araddr), false, VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_arburst", &(TOP.s0_axi_arburst), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_arcache", &(TOP.s0_axi_arcache), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_arid", &(TOP.s0_axi_arid), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_arlen", &(TOP.s0_axi_arlen), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_arlock", &(TOP.s0_axi_arlock), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_arprot", &(TOP.s0_axi_arprot), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_arready", &(TOP.s0_axi_arready), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_arsize", &(TOP.s0_axi_arsize), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_arvalid", &(TOP.s0_axi_arvalid), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_awaddr", &(TOP.s0_axi_awaddr), false, VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_awburst", &(TOP.s0_axi_awburst), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_awcache", &(TOP.s0_axi_awcache), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_awid", &(TOP.s0_axi_awid), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_awlen", &(TOP.s0_axi_awlen), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_awlock", &(TOP.s0_axi_awlock), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_awprot", &(TOP.s0_axi_awprot), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_awready", &(TOP.s0_axi_awready), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_awsize", &(TOP.s0_axi_awsize), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_awvalid", &(TOP.s0_axi_awvalid), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_bid", &(TOP.s0_axi_bid), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_bready", &(TOP.s0_axi_bready), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_bresp", &(TOP.s0_axi_bresp), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_bvalid", &(TOP.s0_axi_bvalid), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_rdata", &(TOP.s0_axi_rdata), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_rid", &(TOP.s0_axi_rid), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_rlast", &(TOP.s0_axi_rlast), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_rready", &(TOP.s0_axi_rready), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_rresp", &(TOP.s0_axi_rresp), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_rvalid", &(TOP.s0_axi_rvalid), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_wdata", &(TOP.s0_axi_wdata), false, VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_wlast", &(TOP.s0_axi_wlast), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_wready", &(TOP.s0_axi_wready), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_wstrb", &(TOP.s0_axi_wstrb), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0_axi_wvalid", &(TOP.s0_axi_wvalid), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_araddr", &(TOP.s1_axi_araddr), false, VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_arburst", &(TOP.s1_axi_arburst), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_arcache", &(TOP.s1_axi_arcache), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_arid", &(TOP.s1_axi_arid), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_arlen", &(TOP.s1_axi_arlen), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_arlock", &(TOP.s1_axi_arlock), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_arprot", &(TOP.s1_axi_arprot), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_arready", &(TOP.s1_axi_arready), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_arsize", &(TOP.s1_axi_arsize), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_arvalid", &(TOP.s1_axi_arvalid), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_awaddr", &(TOP.s1_axi_awaddr), false, VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_awburst", &(TOP.s1_axi_awburst), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_awcache", &(TOP.s1_axi_awcache), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_awid", &(TOP.s1_axi_awid), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_awlen", &(TOP.s1_axi_awlen), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_awlock", &(TOP.s1_axi_awlock), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_awprot", &(TOP.s1_axi_awprot), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_awready", &(TOP.s1_axi_awready), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_awsize", &(TOP.s1_axi_awsize), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_awvalid", &(TOP.s1_axi_awvalid), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_bid", &(TOP.s1_axi_bid), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_bready", &(TOP.s1_axi_bready), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_bresp", &(TOP.s1_axi_bresp), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_bvalid", &(TOP.s1_axi_bvalid), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_rdata", &(TOP.s1_axi_rdata), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_rid", &(TOP.s1_axi_rid), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_rlast", &(TOP.s1_axi_rlast), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_rready", &(TOP.s1_axi_rready), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_rresp", &(TOP.s1_axi_rresp), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_rvalid", &(TOP.s1_axi_rvalid), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_wdata", &(TOP.s1_axi_wdata), false, VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_wlast", &(TOP.s1_axi_wlast), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_wready", &(TOP.s1_axi_wready), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_wstrb", &(TOP.s1_axi_wstrb), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1_axi_wvalid", &(TOP.s1_axi_wvalid), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"IDW", const_cast<void*>(static_cast<const void*>(&(TOP.weft_axi_mux_flat__DOT__IDW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"MIDW", const_cast<void*>(static_cast<const void*>(&(TOP.weft_axi_mux_flat__DOT__MIDW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"N", const_cast<void*>(static_cast<const void*>(&(TOP.weft_axi_mux_flat__DOT__N))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"clk_i", &(TOP.weft_axi_mux_flat__DOT__clk_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_araddr", &(TOP.weft_axi_mux_flat__DOT__m_axi_araddr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_arburst", &(TOP.weft_axi_mux_flat__DOT__m_axi_arburst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_arcache", &(TOP.weft_axi_mux_flat__DOT__m_axi_arcache), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_arid", &(TOP.weft_axi_mux_flat__DOT__m_axi_arid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_arlen", &(TOP.weft_axi_mux_flat__DOT__m_axi_arlen), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_arlock", &(TOP.weft_axi_mux_flat__DOT__m_axi_arlock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_arprot", &(TOP.weft_axi_mux_flat__DOT__m_axi_arprot), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_arready", &(TOP.weft_axi_mux_flat__DOT__m_axi_arready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_arsize", &(TOP.weft_axi_mux_flat__DOT__m_axi_arsize), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_arvalid", &(TOP.weft_axi_mux_flat__DOT__m_axi_arvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_awaddr", &(TOP.weft_axi_mux_flat__DOT__m_axi_awaddr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_awburst", &(TOP.weft_axi_mux_flat__DOT__m_axi_awburst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_awcache", &(TOP.weft_axi_mux_flat__DOT__m_axi_awcache), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_awid", &(TOP.weft_axi_mux_flat__DOT__m_axi_awid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_awlen", &(TOP.weft_axi_mux_flat__DOT__m_axi_awlen), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_awlock", &(TOP.weft_axi_mux_flat__DOT__m_axi_awlock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_awprot", &(TOP.weft_axi_mux_flat__DOT__m_axi_awprot), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_awready", &(TOP.weft_axi_mux_flat__DOT__m_axi_awready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_awsize", &(TOP.weft_axi_mux_flat__DOT__m_axi_awsize), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_awvalid", &(TOP.weft_axi_mux_flat__DOT__m_axi_awvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_bid", &(TOP.weft_axi_mux_flat__DOT__m_axi_bid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_bready", &(TOP.weft_axi_mux_flat__DOT__m_axi_bready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_bresp", &(TOP.weft_axi_mux_flat__DOT__m_axi_bresp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_bvalid", &(TOP.weft_axi_mux_flat__DOT__m_axi_bvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_rdata", &(TOP.weft_axi_mux_flat__DOT__m_axi_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_rid", &(TOP.weft_axi_mux_flat__DOT__m_axi_rid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_rlast", &(TOP.weft_axi_mux_flat__DOT__m_axi_rlast), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_rready", &(TOP.weft_axi_mux_flat__DOT__m_axi_rready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_rresp", &(TOP.weft_axi_mux_flat__DOT__m_axi_rresp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_rvalid", &(TOP.weft_axi_mux_flat__DOT__m_axi_rvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_wdata", &(TOP.weft_axi_mux_flat__DOT__m_axi_wdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_wlast", &(TOP.weft_axi_mux_flat__DOT__m_axi_wlast), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_wready", &(TOP.weft_axi_mux_flat__DOT__m_axi_wready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_wstrb", &(TOP.weft_axi_mux_flat__DOT__m_axi_wstrb), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"m_axi_wvalid", &(TOP.weft_axi_mux_flat__DOT__m_axi_wvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"mreq", &(TOP.weft_axi_mux_flat__DOT__mreq), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,182,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"mrsp", &(TOP.weft_axi_mux_flat__DOT__mrsp), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,53,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"rst_ni", &(TOP.weft_axi_mux_flat__DOT__rst_ni), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_araddr", &(TOP.weft_axi_mux_flat__DOT__s0_axi_araddr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_arburst", &(TOP.weft_axi_mux_flat__DOT__s0_axi_arburst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_arcache", &(TOP.weft_axi_mux_flat__DOT__s0_axi_arcache), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_arid", &(TOP.weft_axi_mux_flat__DOT__s0_axi_arid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_arlen", &(TOP.weft_axi_mux_flat__DOT__s0_axi_arlen), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_arlock", &(TOP.weft_axi_mux_flat__DOT__s0_axi_arlock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_arprot", &(TOP.weft_axi_mux_flat__DOT__s0_axi_arprot), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_arready", &(TOP.weft_axi_mux_flat__DOT__s0_axi_arready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_arsize", &(TOP.weft_axi_mux_flat__DOT__s0_axi_arsize), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_arvalid", &(TOP.weft_axi_mux_flat__DOT__s0_axi_arvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_awaddr", &(TOP.weft_axi_mux_flat__DOT__s0_axi_awaddr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_awburst", &(TOP.weft_axi_mux_flat__DOT__s0_axi_awburst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_awcache", &(TOP.weft_axi_mux_flat__DOT__s0_axi_awcache), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_awid", &(TOP.weft_axi_mux_flat__DOT__s0_axi_awid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_awlen", &(TOP.weft_axi_mux_flat__DOT__s0_axi_awlen), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_awlock", &(TOP.weft_axi_mux_flat__DOT__s0_axi_awlock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_awprot", &(TOP.weft_axi_mux_flat__DOT__s0_axi_awprot), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_awready", &(TOP.weft_axi_mux_flat__DOT__s0_axi_awready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_awsize", &(TOP.weft_axi_mux_flat__DOT__s0_axi_awsize), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_awvalid", &(TOP.weft_axi_mux_flat__DOT__s0_axi_awvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_bid", &(TOP.weft_axi_mux_flat__DOT__s0_axi_bid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_bready", &(TOP.weft_axi_mux_flat__DOT__s0_axi_bready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_bresp", &(TOP.weft_axi_mux_flat__DOT__s0_axi_bresp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_bvalid", &(TOP.weft_axi_mux_flat__DOT__s0_axi_bvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_rdata", &(TOP.weft_axi_mux_flat__DOT__s0_axi_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_rid", &(TOP.weft_axi_mux_flat__DOT__s0_axi_rid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_rlast", &(TOP.weft_axi_mux_flat__DOT__s0_axi_rlast), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_rready", &(TOP.weft_axi_mux_flat__DOT__s0_axi_rready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_rresp", &(TOP.weft_axi_mux_flat__DOT__s0_axi_rresp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_rvalid", &(TOP.weft_axi_mux_flat__DOT__s0_axi_rvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_wdata", &(TOP.weft_axi_mux_flat__DOT__s0_axi_wdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_wlast", &(TOP.weft_axi_mux_flat__DOT__s0_axi_wlast), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_wready", &(TOP.weft_axi_mux_flat__DOT__s0_axi_wready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_wstrb", &(TOP.weft_axi_mux_flat__DOT__s0_axi_wstrb), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s0_axi_wvalid", &(TOP.weft_axi_mux_flat__DOT__s0_axi_wvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_araddr", &(TOP.weft_axi_mux_flat__DOT__s1_axi_araddr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_arburst", &(TOP.weft_axi_mux_flat__DOT__s1_axi_arburst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_arcache", &(TOP.weft_axi_mux_flat__DOT__s1_axi_arcache), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_arid", &(TOP.weft_axi_mux_flat__DOT__s1_axi_arid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_arlen", &(TOP.weft_axi_mux_flat__DOT__s1_axi_arlen), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_arlock", &(TOP.weft_axi_mux_flat__DOT__s1_axi_arlock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_arprot", &(TOP.weft_axi_mux_flat__DOT__s1_axi_arprot), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_arready", &(TOP.weft_axi_mux_flat__DOT__s1_axi_arready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_arsize", &(TOP.weft_axi_mux_flat__DOT__s1_axi_arsize), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_arvalid", &(TOP.weft_axi_mux_flat__DOT__s1_axi_arvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_awaddr", &(TOP.weft_axi_mux_flat__DOT__s1_axi_awaddr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_awburst", &(TOP.weft_axi_mux_flat__DOT__s1_axi_awburst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_awcache", &(TOP.weft_axi_mux_flat__DOT__s1_axi_awcache), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_awid", &(TOP.weft_axi_mux_flat__DOT__s1_axi_awid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_awlen", &(TOP.weft_axi_mux_flat__DOT__s1_axi_awlen), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_awlock", &(TOP.weft_axi_mux_flat__DOT__s1_axi_awlock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_awprot", &(TOP.weft_axi_mux_flat__DOT__s1_axi_awprot), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_awready", &(TOP.weft_axi_mux_flat__DOT__s1_axi_awready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_awsize", &(TOP.weft_axi_mux_flat__DOT__s1_axi_awsize), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_awvalid", &(TOP.weft_axi_mux_flat__DOT__s1_axi_awvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_bid", &(TOP.weft_axi_mux_flat__DOT__s1_axi_bid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_bready", &(TOP.weft_axi_mux_flat__DOT__s1_axi_bready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_bresp", &(TOP.weft_axi_mux_flat__DOT__s1_axi_bresp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_bvalid", &(TOP.weft_axi_mux_flat__DOT__s1_axi_bvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_rdata", &(TOP.weft_axi_mux_flat__DOT__s1_axi_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_rid", &(TOP.weft_axi_mux_flat__DOT__s1_axi_rid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_rlast", &(TOP.weft_axi_mux_flat__DOT__s1_axi_rlast), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_rready", &(TOP.weft_axi_mux_flat__DOT__s1_axi_rready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_rresp", &(TOP.weft_axi_mux_flat__DOT__s1_axi_rresp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_rvalid", &(TOP.weft_axi_mux_flat__DOT__s1_axi_rvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_wdata", &(TOP.weft_axi_mux_flat__DOT__s1_axi_wdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_wlast", &(TOP.weft_axi_mux_flat__DOT__s1_axi_wlast), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_wready", &(TOP.weft_axi_mux_flat__DOT__s1_axi_wready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_wstrb", &(TOP.weft_axi_mux_flat__DOT__s1_axi_wstrb), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"s1_axi_wvalid", &(TOP.weft_axi_mux_flat__DOT__s1_axi_wvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"sreq", &(TOP.weft_axi_mux_flat__DOT__sreq), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,1 ,180,0);
        __Vscope_weft_axi_mux_flat.varInsert(__Vfinal,"srsp", &(TOP.weft_axi_mux_flat__DOT__srsp), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,1 ,51,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"MaxWTxns", const_cast<void*>(static_cast<const void*>(&(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__MaxWTxns))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"NoSlvPorts", const_cast<void*>(static_cast<const void*>(&(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__NoSlvPorts))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"SelW", const_cast<void*>(static_cast<const void*>(&(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__SelW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"SlvIdWidth", const_cast<void*>(static_cast<const void*>(&(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__SlvIdWidth))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"ar_arb_valid", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__ar_arb_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"ar_grant", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__ar_grant), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"ar_hs", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__ar_hs), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"ar_req", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__ar_req), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"ar_sel", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__ar_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,0,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"aw_arb_valid", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__aw_arb_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"aw_grant", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__aw_grant), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"aw_hs", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__aw_hs), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"aw_req", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__aw_req), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"aw_sel", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__aw_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,0,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"b_bits", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__b_bits), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"b_sel", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__b_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,0,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"clk_i", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__clk_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"mst_req_o", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__mst_req_o), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,182,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"mst_rsp_i", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__mst_rsp_i), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,53,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"r_bits", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__r_bits), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,40,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"r_sel", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__r_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,0,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"rst_ni", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__rst_ni), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"sel_ar_bits", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__sel_ar_bits), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,65,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"sel_aw_bits", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__sel_aw_bits), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,71,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"slv_reqs_i", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__slv_reqs_i), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,1 ,180,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"slv_rsps_o", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__slv_rsps_o), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,1 ,51,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"w_empty", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__w_empty), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"w_full", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__w_full), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"w_hs", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__w_hs), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"w_pop", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__w_pop), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux.varInsert(__Vfinal,"w_sel", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__w_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_ar_arb.varInsert(__Vfinal,"NumReq", const_cast<void*>(static_cast<const void*>(&(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_ar_arb__DOT__NumReq))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_ar_arb.varInsert(__Vfinal,"SelW", const_cast<void*>(static_cast<const void*>(&(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_ar_arb__DOT__SelW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_ar_arb.varInsert(__Vfinal,"clk_i", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_ar_arb__DOT__clk_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_ar_arb.varInsert(__Vfinal,"grant_o", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_ar_arb__DOT__grant_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_ar_arb.varInsert(__Vfinal,"ready_i", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_ar_arb__DOT__ready_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_ar_arb.varInsert(__Vfinal,"req_i", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_ar_arb__DOT__req_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_ar_arb.varInsert(__Vfinal,"rst_ni", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_ar_arb__DOT__rst_ni), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_ar_arb.varInsert(__Vfinal,"sel_o", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_ar_arb__DOT__sel_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_ar_arb.varInsert(__Vfinal,"valid_o", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_ar_arb__DOT__valid_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_ar_arb__g_rr.varInsert(__Vfinal,"gnt", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_ar_arb__DOT__g_rr__DOT__gnt), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_ar_arb__g_rr.varInsert(__Vfinal,"gnt_masked", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_ar_arb__DOT__g_rr__DOT__gnt_masked), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_ar_arb__g_rr.varInsert(__Vfinal,"gnt_unmasked", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_ar_arb__DOT__g_rr__DOT__gnt_unmasked), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_ar_arb__g_rr.varInsert(__Vfinal,"mask", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_ar_arb__DOT__g_rr__DOT__mask), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_ar_arb__g_rr.varInsert(__Vfinal,"ptr_q", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_ar_arb__DOT__g_rr__DOT__ptr_q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_ar_arb__g_rr.varInsert(__Vfinal,"req_masked", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_ar_arb__DOT__g_rr__DOT__req_masked), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_ar_arb__g_rr__unnamedblk1.varInsert(__Vfinal,"i", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_ar_arb__DOT__g_rr__DOT__unnamedblk1__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_aw_arb.varInsert(__Vfinal,"NumReq", const_cast<void*>(static_cast<const void*>(&(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_aw_arb__DOT__NumReq))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_aw_arb.varInsert(__Vfinal,"SelW", const_cast<void*>(static_cast<const void*>(&(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_aw_arb__DOT__SelW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_aw_arb.varInsert(__Vfinal,"clk_i", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_aw_arb__DOT__clk_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_aw_arb.varInsert(__Vfinal,"grant_o", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_aw_arb__DOT__grant_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_aw_arb.varInsert(__Vfinal,"ready_i", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_aw_arb__DOT__ready_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_aw_arb.varInsert(__Vfinal,"req_i", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_aw_arb__DOT__req_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_aw_arb.varInsert(__Vfinal,"rst_ni", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_aw_arb__DOT__rst_ni), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_aw_arb.varInsert(__Vfinal,"sel_o", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_aw_arb__DOT__sel_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_aw_arb.varInsert(__Vfinal,"valid_o", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_aw_arb__DOT__valid_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_aw_arb__g_rr.varInsert(__Vfinal,"gnt", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_aw_arb__DOT__g_rr__DOT__gnt), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_aw_arb__g_rr.varInsert(__Vfinal,"gnt_masked", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_aw_arb__DOT__g_rr__DOT__gnt_masked), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_aw_arb__g_rr.varInsert(__Vfinal,"gnt_unmasked", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_aw_arb__DOT__g_rr__DOT__gnt_unmasked), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_aw_arb__g_rr.varInsert(__Vfinal,"mask", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_aw_arb__DOT__g_rr__DOT__mask), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_aw_arb__g_rr.varInsert(__Vfinal,"ptr_q", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_aw_arb__DOT__g_rr__DOT__ptr_q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_aw_arb__g_rr.varInsert(__Vfinal,"req_masked", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_aw_arb__DOT__g_rr__DOT__req_masked), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_aw_arb__g_rr__unnamedblk1.varInsert(__Vfinal,"i", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_aw_arb__DOT__g_rr__DOT__unnamedblk1__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_wfifo.varInsert(__Vfinal,"Depth", const_cast<void*>(static_cast<const void*>(&(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_wfifo__DOT__Depth))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_wfifo.varInsert(__Vfinal,"FallThrough", const_cast<void*>(static_cast<const void*>(&(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_wfifo__DOT__FallThrough))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_wfifo.varInsert(__Vfinal,"PtrW", const_cast<void*>(static_cast<const void*>(&(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_wfifo__DOT__PtrW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_wfifo.varInsert(__Vfinal,"UsgW", const_cast<void*>(static_cast<const void*>(&(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_wfifo__DOT__UsgW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_wfifo.varInsert(__Vfinal,"clk_i", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_wfifo__DOT__clk_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_wfifo.varInsert(__Vfinal,"do_pop", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_wfifo__DOT__do_pop), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_wfifo.varInsert(__Vfinal,"do_push", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_wfifo__DOT__do_push), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_wfifo.varInsert(__Vfinal,"empty_o", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_wfifo__DOT__empty_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_wfifo.varInsert(__Vfinal,"flush_i", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_wfifo__DOT__flush_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_wfifo.varInsert(__Vfinal,"full_o", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_wfifo__DOT__full_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_wfifo.varInsert(__Vfinal,"mem", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_wfifo__DOT__mem), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,7 ,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_wfifo.varInsert(__Vfinal,"pop_i", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_wfifo__DOT__pop_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_wfifo.varInsert(__Vfinal,"push_i", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_wfifo__DOT__push_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_wfifo.varInsert(__Vfinal,"rd_ptr_q", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_wfifo__DOT__rd_ptr_q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_wfifo.varInsert(__Vfinal,"rdata_o", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_wfifo__DOT__rdata_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_wfifo.varInsert(__Vfinal,"rst_ni", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_wfifo__DOT__rst_ni), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_wfifo.varInsert(__Vfinal,"usage_o", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_wfifo__DOT__usage_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_wfifo.varInsert(__Vfinal,"usage_q", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_wfifo__DOT__usage_q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_wfifo.varInsert(__Vfinal,"wdata_i", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_wfifo__DOT__wdata_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,0,0);
        __Vscope_weft_axi_mux_flat__i_mux__i_wfifo.varInsert(__Vfinal,"wr_ptr_q", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__i_wfifo__DOT__wr_ptr_q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_weft_axi_mux_flat__i_mux__unnamedblk1.varInsert(__Vfinal,"i", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__unnamedblk1__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_weft_axi_mux_flat__i_mux__unnamedblk2.varInsert(__Vfinal,"i", &(TOP.weft_axi_mux_flat__DOT__i_mux__DOT__unnamedblk2__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_weft_axi_pkg.varInsert(__Vfinal,"BURST_FIXED", const_cast<void*>(static_cast<const void*>(&(TOP__weft_axi_pkg.BURST_FIXED))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_pkg.varInsert(__Vfinal,"BURST_INCR", const_cast<void*>(static_cast<const void*>(&(TOP__weft_axi_pkg.BURST_INCR))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_pkg.varInsert(__Vfinal,"BURST_WRAP", const_cast<void*>(static_cast<const void*>(&(TOP__weft_axi_pkg.BURST_WRAP))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_pkg.varInsert(__Vfinal,"RESP_DECERR", const_cast<void*>(static_cast<const void*>(&(TOP__weft_axi_pkg.RESP_DECERR))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_pkg.varInsert(__Vfinal,"RESP_EXOKAY", const_cast<void*>(static_cast<const void*>(&(TOP__weft_axi_pkg.RESP_EXOKAY))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_pkg.varInsert(__Vfinal,"RESP_OKAY", const_cast<void*>(static_cast<const void*>(&(TOP__weft_axi_pkg.RESP_OKAY))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_weft_axi_pkg.varInsert(__Vfinal,"RESP_SLVERR", const_cast<void*>(static_cast<const void*>(&(TOP__weft_axi_pkg.RESP_SLVERR))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
    }
}
