// weft_axi_err_slv_flat.sv — flat-port harness for weft_axi_err_slv (single subordinate port).
// Generated by gen_err_flat.py. External master drives s_axi_*; every access is
// answered with an AXI error (DECERR). Used by test_err_slv.py (cocotbext-axi).
`include "weft_axi_typedef.svh"
`default_nettype none
module weft_axi_err_slv_flat import weft_axi_pkg::*; (
  input  wire clk_i, rst_ni,
  input  wire [3:0] s_axi_awid,
  input  wire [31:0] s_axi_awaddr,
  input  wire [7:0] s_axi_awlen,
  input  wire [2:0] s_axi_awsize,
  input  wire [1:0] s_axi_awburst,
  input  wire s_axi_awlock,
  input  wire [3:0] s_axi_awcache,
  input  wire [2:0] s_axi_awprot,
  input  wire s_axi_awvalid,
  output wire s_axi_awready,
  input  wire [31:0] s_axi_wdata,
  input  wire [3:0] s_axi_wstrb,
  input  wire s_axi_wlast,
  input  wire s_axi_wvalid,
  output wire s_axi_wready,
  output wire [3:0] s_axi_bid,
  output wire [1:0] s_axi_bresp,
  output wire s_axi_bvalid,
  input  wire s_axi_bready,
  input  wire [3:0] s_axi_arid,
  input  wire [31:0] s_axi_araddr,
  input  wire [7:0] s_axi_arlen,
  input  wire [2:0] s_axi_arsize,
  input  wire [1:0] s_axi_arburst,
  input  wire s_axi_arlock,
  input  wire [3:0] s_axi_arcache,
  input  wire [2:0] s_axi_arprot,
  input  wire s_axi_arvalid,
  output wire s_axi_arready,
  output wire [3:0] s_axi_rid,
  output wire [31:0] s_axi_rdata,
  output wire [1:0] s_axi_rresp,
  output wire s_axi_rlast,
  output wire s_axi_rvalid,
  input  wire s_axi_rready
);
  typedef logic [31:0] addr_t; typedef logic [4-1:0] id_t; typedef logic [31:0] data_t; typedef logic [3:0] strb_t; typedef logic user_t;
  `WEFT_AXI_TYPEDEF_ALL(x, addr_t, id_t, data_t, strb_t, user_t)
  x_req_t rq; x_rsp_t rs;

  weft_axi_err_slv #(.req_t(x_req_t),.rsp_t(x_rsp_t),.Resp(RESP_DECERR))
    i_err(.clk_i(clk_i),.rst_ni(rst_ni),.slv_req_i(rq),.slv_rsp_o(rs));

  always_comb begin
    rq='0;
    rq.aw.id=s_axi_awid; rq.aw.addr=s_axi_awaddr; rq.aw.len=s_axi_awlen; rq.aw.size=s_axi_awsize; rq.aw.burst=s_axi_awburst; rq.aw.lock=s_axi_awlock; rq.aw.cache=s_axi_awcache; rq.aw.prot=s_axi_awprot; rq.aw_valid=s_axi_awvalid;
    rq.w.data=s_axi_wdata; rq.w.strb=s_axi_wstrb; rq.w.last=s_axi_wlast; rq.w_valid=s_axi_wvalid;
    rq.b_ready=s_axi_bready;
    rq.ar.id=s_axi_arid; rq.ar.addr=s_axi_araddr; rq.ar.len=s_axi_arlen; rq.ar.size=s_axi_arsize; rq.ar.burst=s_axi_arburst; rq.ar.lock=s_axi_arlock; rq.ar.cache=s_axi_arcache; rq.ar.prot=s_axi_arprot; rq.ar_valid=s_axi_arvalid;
    rq.r_ready=s_axi_rready;
  end
  assign s_axi_awready=rs.aw_ready; assign s_axi_wready=rs.w_ready;
  assign s_axi_bid=rs.b.id; assign s_axi_bresp=rs.b.resp; assign s_axi_bvalid=rs.b_valid;
  assign s_axi_arready=rs.ar_ready;
  assign s_axi_rid=rs.r.id; assign s_axi_rdata=rs.r.data; assign s_axi_rresp=rs.r.resp; assign s_axi_rlast=rs.r.last; assign s_axi_rvalid=rs.r_valid;
endmodule
`default_nettype wire