// weft_axi_mux_flat.sv — flat-port harness for weft_axi_mux (2 managers -> 1 subordinate).
// Generated by gen_mux_flat.py. s0_axi/s1_axi are subordinate ports (external masters
// drive them); m_axi is the manager port (drives an AxiRam). Master ID width = 5.
`include "weft_axi_typedef.svh"
`default_nettype none
module weft_axi_mux_flat (
  input  wire clk_i, rst_ni,
  input wire [3:0] s0_axi_awid,
  input wire [31:0] s0_axi_awaddr,
  input wire [7:0] s0_axi_awlen,
  input wire [2:0] s0_axi_awsize,
  input wire [1:0] s0_axi_awburst,
  input wire s0_axi_awlock,
  input wire [3:0] s0_axi_awcache,
  input wire [2:0] s0_axi_awprot,
  input wire s0_axi_awvalid,
  output wire s0_axi_awready,
  input wire [31:0] s0_axi_wdata,
  input wire [3:0] s0_axi_wstrb,
  input wire s0_axi_wlast,
  input wire s0_axi_wvalid,
  output wire s0_axi_wready,
  output wire [3:0] s0_axi_bid,
  output wire [1:0] s0_axi_bresp,
  output wire s0_axi_bvalid,
  input wire s0_axi_bready,
  input wire [3:0] s0_axi_arid,
  input wire [31:0] s0_axi_araddr,
  input wire [7:0] s0_axi_arlen,
  input wire [2:0] s0_axi_arsize,
  input wire [1:0] s0_axi_arburst,
  input wire s0_axi_arlock,
  input wire [3:0] s0_axi_arcache,
  input wire [2:0] s0_axi_arprot,
  input wire s0_axi_arvalid,
  output wire s0_axi_arready,
  output wire [3:0] s0_axi_rid,
  output wire [31:0] s0_axi_rdata,
  output wire [1:0] s0_axi_rresp,
  output wire s0_axi_rlast,
  output wire s0_axi_rvalid,
  input wire s0_axi_rready,
  input wire [3:0] s1_axi_awid,
  input wire [31:0] s1_axi_awaddr,
  input wire [7:0] s1_axi_awlen,
  input wire [2:0] s1_axi_awsize,
  input wire [1:0] s1_axi_awburst,
  input wire s1_axi_awlock,
  input wire [3:0] s1_axi_awcache,
  input wire [2:0] s1_axi_awprot,
  input wire s1_axi_awvalid,
  output wire s1_axi_awready,
  input wire [31:0] s1_axi_wdata,
  input wire [3:0] s1_axi_wstrb,
  input wire s1_axi_wlast,
  input wire s1_axi_wvalid,
  output wire s1_axi_wready,
  output wire [3:0] s1_axi_bid,
  output wire [1:0] s1_axi_bresp,
  output wire s1_axi_bvalid,
  input wire s1_axi_bready,
  input wire [3:0] s1_axi_arid,
  input wire [31:0] s1_axi_araddr,
  input wire [7:0] s1_axi_arlen,
  input wire [2:0] s1_axi_arsize,
  input wire [1:0] s1_axi_arburst,
  input wire s1_axi_arlock,
  input wire [3:0] s1_axi_arcache,
  input wire [2:0] s1_axi_arprot,
  input wire s1_axi_arvalid,
  output wire s1_axi_arready,
  output wire [3:0] s1_axi_rid,
  output wire [31:0] s1_axi_rdata,
  output wire [1:0] s1_axi_rresp,
  output wire s1_axi_rlast,
  output wire s1_axi_rvalid,
  input wire s1_axi_rready,
  output wire [4:0] m_axi_awid,
  output wire [31:0] m_axi_awaddr,
  output wire [7:0] m_axi_awlen,
  output wire [2:0] m_axi_awsize,
  output wire [1:0] m_axi_awburst,
  output wire m_axi_awlock,
  output wire [3:0] m_axi_awcache,
  output wire [2:0] m_axi_awprot,
  output wire m_axi_awvalid,
  input wire m_axi_awready,
  output wire [31:0] m_axi_wdata,
  output wire [3:0] m_axi_wstrb,
  output wire m_axi_wlast,
  output wire m_axi_wvalid,
  input wire m_axi_wready,
  input wire [4:0] m_axi_bid,
  input wire [1:0] m_axi_bresp,
  input wire m_axi_bvalid,
  output wire m_axi_bready,
  output wire [4:0] m_axi_arid,
  output wire [31:0] m_axi_araddr,
  output wire [7:0] m_axi_arlen,
  output wire [2:0] m_axi_arsize,
  output wire [1:0] m_axi_arburst,
  output wire m_axi_arlock,
  output wire [3:0] m_axi_arcache,
  output wire [2:0] m_axi_arprot,
  output wire m_axi_arvalid,
  input wire m_axi_arready,
  input wire [4:0] m_axi_rid,
  input wire [31:0] m_axi_rdata,
  input wire [1:0] m_axi_rresp,
  input wire m_axi_rlast,
  input wire m_axi_rvalid,
  output wire m_axi_rready
);
  import weft_axi_pkg::*;
  localparam int N=2, IDW=4, MIDW=5;
  typedef logic [31:0] addr_t; typedef logic [31:0] data_t; typedef logic [3:0] strb_t; typedef logic user_t;
  typedef logic [IDW-1:0] sid_t; typedef logic [MIDW-1:0] mid_t;
  `WEFT_AXI_TYPEDEF_ALL(s, addr_t, sid_t, data_t, strb_t, user_t)
  `WEFT_AXI_TYPEDEF_ALL(m, addr_t, mid_t, data_t, strb_t, user_t)
  s_req_t sreq [N]; s_rsp_t srsp [N]; m_req_t mreq; m_rsp_t mrsp;

  weft_axi_mux #(.NoSlvPorts(N),.SlvIdWidth(IDW),.MaxWTxns(8),
    .slv_req_t(s_req_t),.slv_rsp_t(s_rsp_t),.mst_req_t(m_req_t),.mst_rsp_t(m_rsp_t)) i_mux (
    .clk_i(clk_i),.rst_ni(rst_ni),.slv_reqs_i(sreq),.slv_rsps_o(srsp),.mst_req_o(mreq),.mst_rsp_i(mrsp));

  always_comb begin
    sreq[0]='0;
    sreq[0].aw.id=s0_axi_awid; sreq[0].aw.addr=s0_axi_awaddr; sreq[0].aw.len=s0_axi_awlen; sreq[0].aw.size=s0_axi_awsize; sreq[0].aw.burst=s0_axi_awburst; sreq[0].aw.lock=s0_axi_awlock; sreq[0].aw.cache=s0_axi_awcache; sreq[0].aw.prot=s0_axi_awprot; sreq[0].aw_valid=s0_axi_awvalid;
    sreq[0].w.data=s0_axi_wdata; sreq[0].w.strb=s0_axi_wstrb; sreq[0].w.last=s0_axi_wlast; sreq[0].w_valid=s0_axi_wvalid;
    sreq[0].b_ready=s0_axi_bready;
    sreq[0].ar.id=s0_axi_arid; sreq[0].ar.addr=s0_axi_araddr; sreq[0].ar.len=s0_axi_arlen; sreq[0].ar.size=s0_axi_arsize; sreq[0].ar.burst=s0_axi_arburst; sreq[0].ar.lock=s0_axi_arlock; sreq[0].ar.cache=s0_axi_arcache; sreq[0].ar.prot=s0_axi_arprot; sreq[0].ar_valid=s0_axi_arvalid;
    sreq[0].r_ready=s0_axi_rready;
    sreq[1]='0;
    sreq[1].aw.id=s1_axi_awid; sreq[1].aw.addr=s1_axi_awaddr; sreq[1].aw.len=s1_axi_awlen; sreq[1].aw.size=s1_axi_awsize; sreq[1].aw.burst=s1_axi_awburst; sreq[1].aw.lock=s1_axi_awlock; sreq[1].aw.cache=s1_axi_awcache; sreq[1].aw.prot=s1_axi_awprot; sreq[1].aw_valid=s1_axi_awvalid;
    sreq[1].w.data=s1_axi_wdata; sreq[1].w.strb=s1_axi_wstrb; sreq[1].w.last=s1_axi_wlast; sreq[1].w_valid=s1_axi_wvalid;
    sreq[1].b_ready=s1_axi_bready;
    sreq[1].ar.id=s1_axi_arid; sreq[1].ar.addr=s1_axi_araddr; sreq[1].ar.len=s1_axi_arlen; sreq[1].ar.size=s1_axi_arsize; sreq[1].ar.burst=s1_axi_arburst; sreq[1].ar.lock=s1_axi_arlock; sreq[1].ar.cache=s1_axi_arcache; sreq[1].ar.prot=s1_axi_arprot; sreq[1].ar_valid=s1_axi_arvalid;
    sreq[1].r_ready=s1_axi_rready;
  end
  assign s0_axi_awready=srsp[0].aw_ready; assign s0_axi_wready=srsp[0].w_ready;
  assign s0_axi_bid=srsp[0].b.id; assign s0_axi_bresp=srsp[0].b.resp; assign s0_axi_bvalid=srsp[0].b_valid;
  assign s0_axi_arready=srsp[0].ar_ready;
  assign s0_axi_rid=srsp[0].r.id; assign s0_axi_rdata=srsp[0].r.data; assign s0_axi_rresp=srsp[0].r.resp; assign s0_axi_rlast=srsp[0].r.last; assign s0_axi_rvalid=srsp[0].r_valid;
  assign s1_axi_awready=srsp[1].aw_ready; assign s1_axi_wready=srsp[1].w_ready;
  assign s1_axi_bid=srsp[1].b.id; assign s1_axi_bresp=srsp[1].b.resp; assign s1_axi_bvalid=srsp[1].b_valid;
  assign s1_axi_arready=srsp[1].ar_ready;
  assign s1_axi_rid=srsp[1].r.id; assign s1_axi_rdata=srsp[1].r.data; assign s1_axi_rresp=srsp[1].r.resp; assign s1_axi_rlast=srsp[1].r.last; assign s1_axi_rvalid=srsp[1].r_valid;

  // m_axi manager port <- mreq / -> mrsp
  assign m_axi_awid=mreq.aw.id; assign m_axi_awaddr=mreq.aw.addr; assign m_axi_awlen=mreq.aw.len; assign m_axi_awsize=mreq.aw.size; assign m_axi_awburst=mreq.aw.burst; assign m_axi_awlock=mreq.aw.lock; assign m_axi_awcache=mreq.aw.cache; assign m_axi_awprot=mreq.aw.prot; assign m_axi_awvalid=mreq.aw_valid;
  assign m_axi_wdata=mreq.w.data; assign m_axi_wstrb=mreq.w.strb; assign m_axi_wlast=mreq.w.last; assign m_axi_wvalid=mreq.w_valid;
  assign m_axi_bready=mreq.b_ready;
  assign m_axi_arid=mreq.ar.id; assign m_axi_araddr=mreq.ar.addr; assign m_axi_arlen=mreq.ar.len; assign m_axi_arsize=mreq.ar.size; assign m_axi_arburst=mreq.ar.burst; assign m_axi_arlock=mreq.ar.lock; assign m_axi_arcache=mreq.ar.cache; assign m_axi_arprot=mreq.ar.prot; assign m_axi_arvalid=mreq.ar_valid;
  assign m_axi_rready=mreq.r_ready;
  always_comb begin
    mrsp='0;
    mrsp.aw_ready=m_axi_awready; mrsp.w_ready=m_axi_wready;
    mrsp.b.id=m_axi_bid; mrsp.b.resp=m_axi_bresp; mrsp.b_valid=m_axi_bvalid;
    mrsp.ar_ready=m_axi_arready;
    mrsp.r.id=m_axi_rid; mrsp.r.data=m_axi_rdata; mrsp.r.resp=m_axi_rresp; mrsp.r.last=m_axi_rlast; mrsp.r_valid=m_axi_rvalid;
  end
endmodule
`default_nettype wire