// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"
class Vtop_weft_axi_pkg;


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:
    // CELLS
    Vtop_weft_axi_pkg* __PVT__weft_axi_pkg;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk_i,0,0);
        VL_IN8(rst_ni,0,0);
        VL_IN8(s0_axi_awid,3,0);
        VL_IN8(s0_axi_awlen,7,0);
        VL_IN8(s0_axi_awsize,2,0);
        VL_IN8(s0_axi_awburst,1,0);
        VL_IN8(s0_axi_awlock,0,0);
        VL_IN8(s0_axi_awcache,3,0);
        VL_IN8(s0_axi_awprot,2,0);
        VL_IN8(s0_axi_awvalid,0,0);
        VL_OUT8(s0_axi_awready,0,0);
        VL_IN8(s0_axi_wstrb,3,0);
        VL_IN8(s0_axi_wlast,0,0);
        VL_IN8(s0_axi_wvalid,0,0);
        VL_OUT8(s0_axi_wready,0,0);
        VL_OUT8(s0_axi_bid,3,0);
        VL_OUT8(s0_axi_bresp,1,0);
        VL_OUT8(s0_axi_bvalid,0,0);
        VL_IN8(s0_axi_bready,0,0);
        VL_IN8(s0_axi_arid,3,0);
        VL_IN8(s0_axi_arlen,7,0);
        VL_IN8(s0_axi_arsize,2,0);
        VL_IN8(s0_axi_arburst,1,0);
        VL_IN8(s0_axi_arlock,0,0);
        VL_IN8(s0_axi_arcache,3,0);
        VL_IN8(s0_axi_arprot,2,0);
        VL_IN8(s0_axi_arvalid,0,0);
        VL_OUT8(s0_axi_arready,0,0);
        VL_OUT8(s0_axi_rid,3,0);
        VL_OUT8(s0_axi_rresp,1,0);
        VL_OUT8(s0_axi_rlast,0,0);
        VL_OUT8(s0_axi_rvalid,0,0);
        VL_IN8(s0_axi_rready,0,0);
        VL_IN8(s1_axi_awid,3,0);
        VL_IN8(s1_axi_awlen,7,0);
        VL_IN8(s1_axi_awsize,2,0);
        VL_IN8(s1_axi_awburst,1,0);
        VL_IN8(s1_axi_awlock,0,0);
        VL_IN8(s1_axi_awcache,3,0);
        VL_IN8(s1_axi_awprot,2,0);
        VL_IN8(s1_axi_awvalid,0,0);
        VL_OUT8(s1_axi_awready,0,0);
        VL_IN8(s1_axi_wstrb,3,0);
        VL_IN8(s1_axi_wlast,0,0);
        VL_IN8(s1_axi_wvalid,0,0);
        VL_OUT8(s1_axi_wready,0,0);
        VL_OUT8(s1_axi_bid,3,0);
        VL_OUT8(s1_axi_bresp,1,0);
        VL_OUT8(s1_axi_bvalid,0,0);
        VL_IN8(s1_axi_bready,0,0);
        VL_IN8(s1_axi_arid,3,0);
        VL_IN8(s1_axi_arlen,7,0);
        VL_IN8(s1_axi_arsize,2,0);
        VL_IN8(s1_axi_arburst,1,0);
        VL_IN8(s1_axi_arlock,0,0);
        VL_IN8(s1_axi_arcache,3,0);
        VL_IN8(s1_axi_arprot,2,0);
        VL_IN8(s1_axi_arvalid,0,0);
        VL_OUT8(s1_axi_arready,0,0);
        VL_OUT8(s1_axi_rid,3,0);
        VL_OUT8(s1_axi_rresp,1,0);
        VL_OUT8(s1_axi_rlast,0,0);
        VL_OUT8(s1_axi_rvalid,0,0);
        VL_IN8(s1_axi_rready,0,0);
    };
    struct {
        VL_OUT8(m0_axi_awid,4,0);
        VL_OUT8(m0_axi_awlen,7,0);
        VL_OUT8(m0_axi_awsize,2,0);
        VL_OUT8(m0_axi_awburst,1,0);
        VL_OUT8(m0_axi_awlock,0,0);
        VL_OUT8(m0_axi_awcache,3,0);
        VL_OUT8(m0_axi_awprot,2,0);
        VL_OUT8(m0_axi_awvalid,0,0);
        VL_IN8(m0_axi_awready,0,0);
        VL_OUT8(m0_axi_wstrb,3,0);
        VL_OUT8(m0_axi_wlast,0,0);
        VL_OUT8(m0_axi_wvalid,0,0);
        VL_IN8(m0_axi_wready,0,0);
        VL_IN8(m0_axi_bid,4,0);
        VL_IN8(m0_axi_bresp,1,0);
        VL_IN8(m0_axi_bvalid,0,0);
        VL_OUT8(m0_axi_bready,0,0);
        VL_OUT8(m0_axi_arid,4,0);
        VL_OUT8(m0_axi_arlen,7,0);
        VL_OUT8(m0_axi_arsize,2,0);
        VL_OUT8(m0_axi_arburst,1,0);
        VL_OUT8(m0_axi_arlock,0,0);
        VL_OUT8(m0_axi_arcache,3,0);
        VL_OUT8(m0_axi_arprot,2,0);
        VL_OUT8(m0_axi_arvalid,0,0);
        VL_IN8(m0_axi_arready,0,0);
        VL_IN8(m0_axi_rid,4,0);
        VL_IN8(m0_axi_rresp,1,0);
        VL_IN8(m0_axi_rlast,0,0);
        VL_IN8(m0_axi_rvalid,0,0);
        VL_OUT8(m0_axi_rready,0,0);
        VL_OUT8(m1_axi_awid,4,0);
        VL_OUT8(m1_axi_awlen,7,0);
        VL_OUT8(m1_axi_awsize,2,0);
        VL_OUT8(m1_axi_awburst,1,0);
        VL_OUT8(m1_axi_awlock,0,0);
        VL_OUT8(m1_axi_awcache,3,0);
        VL_OUT8(m1_axi_awprot,2,0);
        VL_OUT8(m1_axi_awvalid,0,0);
        VL_IN8(m1_axi_awready,0,0);
        VL_OUT8(m1_axi_wstrb,3,0);
        VL_OUT8(m1_axi_wlast,0,0);
        VL_OUT8(m1_axi_wvalid,0,0);
        VL_IN8(m1_axi_wready,0,0);
        VL_IN8(m1_axi_bid,4,0);
        VL_IN8(m1_axi_bresp,1,0);
        VL_IN8(m1_axi_bvalid,0,0);
        VL_OUT8(m1_axi_bready,0,0);
        VL_OUT8(m1_axi_arid,4,0);
        VL_OUT8(m1_axi_arlen,7,0);
        VL_OUT8(m1_axi_arsize,2,0);
        VL_OUT8(m1_axi_arburst,1,0);
        VL_OUT8(m1_axi_arlock,0,0);
        VL_OUT8(m1_axi_arcache,3,0);
        VL_OUT8(m1_axi_arprot,2,0);
        VL_OUT8(m1_axi_arvalid,0,0);
        VL_IN8(m1_axi_arready,0,0);
        VL_IN8(m1_axi_rid,4,0);
        VL_IN8(m1_axi_rresp,1,0);
        VL_IN8(m1_axi_rlast,0,0);
        VL_IN8(m1_axi_rvalid,0,0);
        VL_OUT8(m1_axi_rready,0,0);
        CData/*0:0*/ weft_axi_xbar_flat__DOT__clk_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__rst_ni;
    };
    struct {
        CData/*3:0*/ weft_axi_xbar_flat__DOT__s0_axi_awid;
        CData/*7:0*/ weft_axi_xbar_flat__DOT__s0_axi_awlen;
        CData/*2:0*/ weft_axi_xbar_flat__DOT__s0_axi_awsize;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__s0_axi_awburst;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s0_axi_awlock;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__s0_axi_awcache;
        CData/*2:0*/ weft_axi_xbar_flat__DOT__s0_axi_awprot;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s0_axi_awvalid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s0_axi_awready;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__s0_axi_wstrb;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s0_axi_wlast;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s0_axi_wvalid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s0_axi_wready;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__s0_axi_bid;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__s0_axi_bresp;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s0_axi_bvalid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s0_axi_bready;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__s0_axi_arid;
        CData/*7:0*/ weft_axi_xbar_flat__DOT__s0_axi_arlen;
        CData/*2:0*/ weft_axi_xbar_flat__DOT__s0_axi_arsize;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__s0_axi_arburst;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s0_axi_arlock;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__s0_axi_arcache;
        CData/*2:0*/ weft_axi_xbar_flat__DOT__s0_axi_arprot;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s0_axi_arvalid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s0_axi_arready;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__s0_axi_rid;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__s0_axi_rresp;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s0_axi_rlast;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s0_axi_rvalid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s0_axi_rready;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__s1_axi_awid;
        CData/*7:0*/ weft_axi_xbar_flat__DOT__s1_axi_awlen;
        CData/*2:0*/ weft_axi_xbar_flat__DOT__s1_axi_awsize;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__s1_axi_awburst;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s1_axi_awlock;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__s1_axi_awcache;
        CData/*2:0*/ weft_axi_xbar_flat__DOT__s1_axi_awprot;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s1_axi_awvalid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s1_axi_awready;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__s1_axi_wstrb;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s1_axi_wlast;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s1_axi_wvalid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s1_axi_wready;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__s1_axi_bid;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__s1_axi_bresp;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s1_axi_bvalid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s1_axi_bready;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__s1_axi_arid;
        CData/*7:0*/ weft_axi_xbar_flat__DOT__s1_axi_arlen;
        CData/*2:0*/ weft_axi_xbar_flat__DOT__s1_axi_arsize;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__s1_axi_arburst;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s1_axi_arlock;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__s1_axi_arcache;
        CData/*2:0*/ weft_axi_xbar_flat__DOT__s1_axi_arprot;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s1_axi_arvalid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s1_axi_arready;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__s1_axi_rid;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__s1_axi_rresp;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s1_axi_rlast;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s1_axi_rvalid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__s1_axi_rready;
        CData/*4:0*/ weft_axi_xbar_flat__DOT__m0_axi_awid;
        CData/*7:0*/ weft_axi_xbar_flat__DOT__m0_axi_awlen;
    };
    struct {
        CData/*2:0*/ weft_axi_xbar_flat__DOT__m0_axi_awsize;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__m0_axi_awburst;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m0_axi_awlock;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__m0_axi_awcache;
        CData/*2:0*/ weft_axi_xbar_flat__DOT__m0_axi_awprot;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m0_axi_awvalid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m0_axi_awready;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__m0_axi_wstrb;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m0_axi_wlast;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m0_axi_wvalid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m0_axi_wready;
        CData/*4:0*/ weft_axi_xbar_flat__DOT__m0_axi_bid;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__m0_axi_bresp;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m0_axi_bvalid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m0_axi_bready;
        CData/*4:0*/ weft_axi_xbar_flat__DOT__m0_axi_arid;
        CData/*7:0*/ weft_axi_xbar_flat__DOT__m0_axi_arlen;
        CData/*2:0*/ weft_axi_xbar_flat__DOT__m0_axi_arsize;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__m0_axi_arburst;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m0_axi_arlock;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__m0_axi_arcache;
        CData/*2:0*/ weft_axi_xbar_flat__DOT__m0_axi_arprot;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m0_axi_arvalid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m0_axi_arready;
        CData/*4:0*/ weft_axi_xbar_flat__DOT__m0_axi_rid;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__m0_axi_rresp;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m0_axi_rlast;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m0_axi_rvalid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m0_axi_rready;
        CData/*4:0*/ weft_axi_xbar_flat__DOT__m1_axi_awid;
        CData/*7:0*/ weft_axi_xbar_flat__DOT__m1_axi_awlen;
        CData/*2:0*/ weft_axi_xbar_flat__DOT__m1_axi_awsize;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__m1_axi_awburst;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m1_axi_awlock;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__m1_axi_awcache;
        CData/*2:0*/ weft_axi_xbar_flat__DOT__m1_axi_awprot;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m1_axi_awvalid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m1_axi_awready;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__m1_axi_wstrb;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m1_axi_wlast;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m1_axi_wvalid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m1_axi_wready;
        CData/*4:0*/ weft_axi_xbar_flat__DOT__m1_axi_bid;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__m1_axi_bresp;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m1_axi_bvalid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m1_axi_bready;
        CData/*4:0*/ weft_axi_xbar_flat__DOT__m1_axi_arid;
        CData/*7:0*/ weft_axi_xbar_flat__DOT__m1_axi_arlen;
        CData/*2:0*/ weft_axi_xbar_flat__DOT__m1_axi_arsize;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__m1_axi_arburst;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m1_axi_arlock;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__m1_axi_arcache;
        CData/*2:0*/ weft_axi_xbar_flat__DOT__m1_axi_arprot;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m1_axi_arvalid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m1_axi_arready;
        CData/*4:0*/ weft_axi_xbar_flat__DOT__m1_axi_rid;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__m1_axi_rresp;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m1_axi_rlast;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m1_axi_rvalid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__m1_axi_rready;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__clk_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__rst_ni;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__aw_idx;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__ar_idx;
    };
    struct {
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__aw_err;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__ar_err;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__aw_sel;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__ar_sel;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__aw_idx;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__ar_idx;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__aw_err;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__ar_err;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__aw_sel;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__ar_sel;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_aw_dec__DOT__idx_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_aw_dec__DOT__dec_valid_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_aw_dec__DOT__dec_error_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_ar_dec__DOT__idx_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_ar_dec__DOT__dec_valid_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_ar_dec__DOT__dec_error_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__clk_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__rst_ni;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__slv_aw_select_i;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__slv_ar_select_i;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__w_port_q;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__r_port_q;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__w_cnt_q;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__r_cnt_q;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__aw_allowed;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__ar_allowed;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__aw_hs;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__b_hs;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__ar_hs;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__r_hs;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__r_last_hs;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_err__DOT__clk_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_err__DOT__rst_ni;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_err__DOT__w_q;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_err__DOT__w_id_q;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_err__DOT__r_q;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_err__DOT__r_id_q;
        CData/*7:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_err__DOT__r_len_q;
        CData/*7:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_err__DOT__r_cnt_q;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_aw_dec__DOT__idx_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_aw_dec__DOT__dec_valid_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_aw_dec__DOT__dec_error_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_ar_dec__DOT__idx_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_ar_dec__DOT__dec_valid_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_ar_dec__DOT__dec_error_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__clk_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__rst_ni;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__slv_aw_select_i;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__slv_ar_select_i;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__w_port_q;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__r_port_q;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__w_cnt_q;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__r_cnt_q;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__aw_allowed;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__ar_allowed;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__aw_hs;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__b_hs;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__ar_hs;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__r_hs;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__r_last_hs;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_err__DOT__clk_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_err__DOT__rst_ni;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_err__DOT__w_q;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_err__DOT__w_id_q;
    };
    struct {
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_err__DOT__r_q;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_err__DOT__r_id_q;
        CData/*7:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_err__DOT__r_len_q;
        CData/*7:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_err__DOT__r_cnt_q;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__clk_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__rst_ni;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__aw_req;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__ar_req;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__aw_grant;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__ar_grant;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__aw_sel;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__ar_sel;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__aw_arb_valid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__ar_arb_valid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__aw_hs;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__ar_hs;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__w_sel;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__w_full;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__w_empty;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__w_pop;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__w_hs;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__b_sel;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__r_sel;
        CData/*7:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__b_bits;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_aw_arb__DOT__clk_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_aw_arb__DOT__rst_ni;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_aw_arb__DOT__req_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_aw_arb__DOT__ready_i;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_aw_arb__DOT__grant_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_aw_arb__DOT__sel_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_aw_arb__DOT__valid_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_aw_arb__DOT__g_rr__DOT__ptr_q;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_aw_arb__DOT__g_rr__DOT__mask;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_aw_arb__DOT__g_rr__DOT__req_masked;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_aw_arb__DOT__g_rr__DOT__gnt_masked;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_aw_arb__DOT__g_rr__DOT__gnt_unmasked;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_aw_arb__DOT__g_rr__DOT__gnt;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_ar_arb__DOT__clk_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_ar_arb__DOT__rst_ni;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_ar_arb__DOT__req_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_ar_arb__DOT__ready_i;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_ar_arb__DOT__grant_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_ar_arb__DOT__sel_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_ar_arb__DOT__valid_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_ar_arb__DOT__g_rr__DOT__ptr_q;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_ar_arb__DOT__g_rr__DOT__mask;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_ar_arb__DOT__g_rr__DOT__req_masked;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_ar_arb__DOT__g_rr__DOT__gnt_masked;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_ar_arb__DOT__g_rr__DOT__gnt_unmasked;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_ar_arb__DOT__g_rr__DOT__gnt;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_wfifo__DOT__clk_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_wfifo__DOT__rst_ni;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_wfifo__DOT__flush_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_wfifo__DOT__wdata_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_wfifo__DOT__push_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_wfifo__DOT__full_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_wfifo__DOT__rdata_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_wfifo__DOT__pop_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_wfifo__DOT__empty_o;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_wfifo__DOT__usage_o;
        CData/*2:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_wfifo__DOT__rd_ptr_q;
        CData/*2:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_wfifo__DOT__wr_ptr_q;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_wfifo__DOT__usage_q;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_wfifo__DOT__do_push;
    };
    struct {
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_wfifo__DOT__do_pop;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__clk_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__rst_ni;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__aw_req;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__ar_req;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__aw_grant;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__ar_grant;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__aw_sel;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__ar_sel;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__aw_arb_valid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__ar_arb_valid;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__aw_hs;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__ar_hs;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__w_sel;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__w_full;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__w_empty;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__w_pop;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__w_hs;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__b_sel;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__r_sel;
        CData/*7:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__b_bits;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_aw_arb__DOT__clk_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_aw_arb__DOT__rst_ni;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_aw_arb__DOT__req_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_aw_arb__DOT__ready_i;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_aw_arb__DOT__grant_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_aw_arb__DOT__sel_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_aw_arb__DOT__valid_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_aw_arb__DOT__g_rr__DOT__ptr_q;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_aw_arb__DOT__g_rr__DOT__mask;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_aw_arb__DOT__g_rr__DOT__req_masked;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_aw_arb__DOT__g_rr__DOT__gnt_masked;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_aw_arb__DOT__g_rr__DOT__gnt_unmasked;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_aw_arb__DOT__g_rr__DOT__gnt;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_ar_arb__DOT__clk_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_ar_arb__DOT__rst_ni;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_ar_arb__DOT__req_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_ar_arb__DOT__ready_i;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_ar_arb__DOT__grant_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_ar_arb__DOT__sel_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_ar_arb__DOT__valid_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_ar_arb__DOT__g_rr__DOT__ptr_q;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_ar_arb__DOT__g_rr__DOT__mask;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_ar_arb__DOT__g_rr__DOT__req_masked;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_ar_arb__DOT__g_rr__DOT__gnt_masked;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_ar_arb__DOT__g_rr__DOT__gnt_unmasked;
        CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_ar_arb__DOT__g_rr__DOT__gnt;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_wfifo__DOT__clk_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_wfifo__DOT__rst_ni;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_wfifo__DOT__flush_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_wfifo__DOT__wdata_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_wfifo__DOT__push_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_wfifo__DOT__full_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_wfifo__DOT__rdata_o;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_wfifo__DOT__pop_i;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_wfifo__DOT__empty_o;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_wfifo__DOT__usage_o;
        CData/*2:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_wfifo__DOT__rd_ptr_q;
        CData/*2:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_wfifo__DOT__wr_ptr_q;
        CData/*3:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_wfifo__DOT__usage_q;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_wfifo__DOT__do_push;
        CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_wfifo__DOT__do_pop;
        CData/*2:0*/ __Vdly__weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_wfifo__DOT__wr_ptr_q;
        CData/*2:0*/ __Vdly__weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_wfifo__DOT__wr_ptr_q;
    };
    struct {
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_ni__0;
        CData/*0:0*/ __VactContinue;
        VL_IN(s0_axi_awaddr,31,0);
        VL_IN(s0_axi_wdata,31,0);
        VL_IN(s0_axi_araddr,31,0);
        VL_OUT(s0_axi_rdata,31,0);
        VL_IN(s1_axi_awaddr,31,0);
        VL_IN(s1_axi_wdata,31,0);
        VL_IN(s1_axi_araddr,31,0);
        VL_OUT(s1_axi_rdata,31,0);
        VL_OUT(m0_axi_awaddr,31,0);
        VL_OUT(m0_axi_wdata,31,0);
        VL_OUT(m0_axi_araddr,31,0);
        VL_IN(m0_axi_rdata,31,0);
        VL_OUT(m1_axi_awaddr,31,0);
        VL_OUT(m1_axi_wdata,31,0);
        VL_OUT(m1_axi_araddr,31,0);
        VL_IN(m1_axi_rdata,31,0);
        IData/*31:0*/ weft_axi_xbar_flat__DOT__s0_axi_awaddr;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__s0_axi_wdata;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__s0_axi_araddr;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__s0_axi_rdata;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__s1_axi_awaddr;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__s1_axi_wdata;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__s1_axi_araddr;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__s1_axi_rdata;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__m0_axi_awaddr;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__m0_axi_wdata;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__m0_axi_araddr;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__m0_axi_rdata;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__m1_axi_awaddr;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__m1_axi_wdata;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__m1_axi_araddr;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__m1_axi_rdata;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_aw_dec__DOT__unnamedblk1__DOT__r;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_ar_dec__DOT__unnamedblk1__DOT__r;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__unnamedblk1__DOT__m;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_aw_dec__DOT__unnamedblk1__DOT__r;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_ar_dec__DOT__unnamedblk1__DOT__r;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__unnamedblk1__DOT__m;
        VlWide<3>/*71:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__sel_aw_bits;
        VlWide<3>/*65:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__sel_ar_bits;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_aw_arb__DOT__g_rr__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_ar_arb__DOT__g_rr__DOT__unnamedblk1__DOT__i;
        VlWide<3>/*71:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__sel_aw_bits;
        VlWide<3>/*65:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__sel_ar_bits;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_aw_arb__DOT__g_rr__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_ar_arb__DOT__g_rr__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ __VactIterCount;
        QData/*63:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_aw_dec__DOT__addr_i;
        VlWide<10>/*319:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_aw_dec__DOT__rules_i;
        QData/*63:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_aw_dec__DOT__addr64;
        QData/*63:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_ar_dec__DOT__addr_i;
        VlWide<10>/*319:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_ar_dec__DOT__rules_i;
        QData/*63:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_ar_dec__DOT__addr64;
        VlWide<6>/*180:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__slv_req_i;
        QData/*51:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__slv_rsp_o;
    };
    struct {
        VlWide<6>/*180:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_err__DOT__slv_req_i;
        QData/*51:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_err__DOT__slv_rsp_o;
        QData/*63:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_aw_dec__DOT__addr_i;
        VlWide<10>/*319:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_aw_dec__DOT__rules_i;
        QData/*63:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_aw_dec__DOT__addr64;
        QData/*63:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_ar_dec__DOT__addr_i;
        VlWide<10>/*319:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_ar_dec__DOT__rules_i;
        QData/*63:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_ar_dec__DOT__addr64;
        VlWide<6>/*180:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__slv_req_i;
        QData/*51:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__slv_rsp_o;
        VlWide<6>/*180:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_err__DOT__slv_req_i;
        QData/*51:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_err__DOT__slv_rsp_o;
        VlWide<6>/*182:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__mst_req_o;
        QData/*53:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__mst_rsp_i;
        QData/*40:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__r_bits;
        VlWide<6>/*182:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__mst_req_o;
        QData/*53:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__mst_rsp_i;
        QData/*40:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__r_bits;
        VlUnpacked<VlWide<6>/*180:0*/, 2> weft_axi_xbar_flat__DOT__sreq;
        VlUnpacked<QData/*51:0*/, 2> weft_axi_xbar_flat__DOT__srsp;
        VlUnpacked<VlWide<6>/*182:0*/, 2> weft_axi_xbar_flat__DOT__mreq;
        VlUnpacked<QData/*53:0*/, 2> weft_axi_xbar_flat__DOT__mrsp;
        VlUnpacked<VlWide<6>/*180:0*/, 2> weft_axi_xbar_flat__DOT__i_xbar__DOT__slv_reqs_i;
        VlUnpacked<QData/*51:0*/, 2> weft_axi_xbar_flat__DOT__i_xbar__DOT__slv_rsps_o;
        VlUnpacked<VlWide<6>/*182:0*/, 2> weft_axi_xbar_flat__DOT__i_xbar__DOT__mst_reqs_o;
        VlUnpacked<QData/*53:0*/, 2> weft_axi_xbar_flat__DOT__i_xbar__DOT__mst_rsps_i;
        VlUnpacked<VlUnpacked<VlWide<6>/*180:0*/, 3>, 2> weft_axi_xbar_flat__DOT__i_xbar__DOT__demux_req;
        VlUnpacked<VlUnpacked<QData/*51:0*/, 3>, 2> weft_axi_xbar_flat__DOT__i_xbar__DOT__demux_rsp;
        VlUnpacked<QData/*51:0*/, 3> weft_axi_xbar_flat__DOT__i_xbar__DOT____Vcellinp__g_slv__BRA__0__KET____DOT__i_demux__mst_rsps_i;
        VlUnpacked<VlWide<6>/*180:0*/, 3> weft_axi_xbar_flat__DOT__i_xbar__DOT____Vcellout__g_slv__BRA__0__KET____DOT__i_demux__mst_reqs_o;
        VlUnpacked<QData/*51:0*/, 3> weft_axi_xbar_flat__DOT__i_xbar__DOT____Vcellinp__g_slv__BRA__1__KET____DOT__i_demux__mst_rsps_i;
        VlUnpacked<VlWide<6>/*180:0*/, 3> weft_axi_xbar_flat__DOT__i_xbar__DOT____Vcellout__g_slv__BRA__1__KET____DOT__i_demux__mst_reqs_o;
        VlUnpacked<VlWide<6>/*180:0*/, 2> weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__mux_req;
        VlUnpacked<QData/*51:0*/, 2> weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__mux_rsp;
        VlUnpacked<VlWide<6>/*180:0*/, 2> weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__mux_req;
        VlUnpacked<QData/*51:0*/, 2> weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__mux_rsp;
        VlUnpacked<VlWide<6>/*180:0*/, 3> weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__mst_reqs_o;
        VlUnpacked<QData/*51:0*/, 3> weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__mst_rsps_i;
        VlUnpacked<VlWide<6>/*180:0*/, 3> weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__mst_reqs_o;
        VlUnpacked<QData/*51:0*/, 3> weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__mst_rsps_i;
        VlUnpacked<VlWide<6>/*180:0*/, 2> weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__slv_reqs_i;
        VlUnpacked<QData/*51:0*/, 2> weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__slv_rsps_o;
        VlUnpacked<CData/*0:0*/, 8> weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_wfifo__DOT__mem;
        VlUnpacked<VlWide<6>/*180:0*/, 2> weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__slv_reqs_i;
        VlUnpacked<QData/*51:0*/, 2> weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__slv_rsps_o;
        VlUnpacked<CData/*0:0*/, 8> weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_wfifo__DOT__mem;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_err__DOT__Resp = 3U;
    static constexpr CData/*1:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_err__DOT__Resp = 3U;
    static constexpr CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_wfifo__DOT__FallThrough = 0U;
    static constexpr CData/*0:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_wfifo__DOT__FallThrough = 0U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__N = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__M = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__IDW = 4U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__MIDW = 5U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__NoSlvPorts = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__NoMstPorts = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__SlvIdWidth = 4U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__NoRules = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__MaxTxns = 8U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__NoDemuxPorts = 3U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__ErrIdx = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__DSelW = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__DecIdxW = 1U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_aw_dec__DOT__NoIndices = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_aw_dec__DOT__NoRules = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_aw_dec__DOT__IdxW = 1U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_ar_dec__DOT__NoIndices = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_ar_dec__DOT__NoRules = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_ar_dec__DOT__IdxW = 1U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__NoMstPorts = 3U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__MaxTxns = 8U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__SelW = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__0__KET____DOT__i_demux__DOT__CntW = 4U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_aw_dec__DOT__NoIndices = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_aw_dec__DOT__NoRules = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_aw_dec__DOT__IdxW = 1U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_ar_dec__DOT__NoIndices = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_ar_dec__DOT__NoRules = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_ar_dec__DOT__IdxW = 1U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__NoMstPorts = 3U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__MaxTxns = 8U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__SelW = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_slv__BRA__1__KET____DOT__i_demux__DOT__CntW = 4U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__NoSlvPorts = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__SlvIdWidth = 4U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__MaxWTxns = 8U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__SelW = 1U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_aw_arb__DOT__NumReq = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_aw_arb__DOT__SelW = 1U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_ar_arb__DOT__NumReq = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_ar_arb__DOT__SelW = 1U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_wfifo__DOT__Depth = 8U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_wfifo__DOT__PtrW = 3U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__0__KET____DOT__i_mux__DOT__i_wfifo__DOT__UsgW = 4U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__NoSlvPorts = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__SlvIdWidth = 4U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__MaxWTxns = 8U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__SelW = 1U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_aw_arb__DOT__NumReq = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_aw_arb__DOT__SelW = 1U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_ar_arb__DOT__NumReq = 2U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_ar_arb__DOT__SelW = 1U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_wfifo__DOT__Depth = 8U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_wfifo__DOT__PtrW = 3U;
    static constexpr IData/*31:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__g_mst__BRA__1__KET____DOT__i_mux__DOT__i_wfifo__DOT__UsgW = 4U;
    static const VlWide<10>/*319:0*/ weft_axi_xbar_flat__DOT__MAP;
    static const VlWide<10>/*319:0*/ weft_axi_xbar_flat__DOT__i_xbar__DOT__AddrMap;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
